// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: user_subscription.
// - Entity ID: 102019aed60fd5e70e28b8911d5cfec408a.
// - Entity Version: 102019af1075be77c3886045ea79d1900cd.
// - Task ID: 69337686982efa550d4aac7f.
// - Task Root ID: 69328003c70740a92a92684f.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for UserSubscriptionTier
 */
export enum UserSubscriptionTier {
  Unspecified = 0,
  Free = 1,
  Premium = 2,
}



/**
 * Interface for UserSubscriptionModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface UserSubscriptionModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  user_id: string;
  tier: UserSubscriptionTier;
  started_date: string;
  expires_date?: string | null;
  is_active: boolean;
}

/**
 * ORM class for UserSubscription entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class UserSubscriptionORM {
  private static instance: UserSubscriptionORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019aed60fd5e70e28b8911d5cfec408a';
    this.entityName = 'user_subscription';
    this.entityVersion = '102019af1075be77c3886045ea79d1900cd';
    this.taskId = '69337686982efa550d4aac7f';
    this.taskRootId = '69328003c70740a92a92684f';
  }

  /**
   * Get singleton instance of UserSubscriptionORM
   */
  public static getInstance(): UserSubscriptionORM {
    if (!UserSubscriptionORM.instance) {
      UserSubscriptionORM.instance = new UserSubscriptionORM();
    }
    
    return UserSubscriptionORM.instance;
  }

  /**
   * Get all UserSubscription records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllUserSubscription(): Promise<UserSubscriptionModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new UserSubscription record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertUserSubscription(data: UserSubscriptionModel[]): Promise<UserSubscriptionModel[]> {
    const structured = data.map((item) => CreateData(UserSubscriptionModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all UserSubscription records
   */
  async purgeAllUserSubscription(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List UserSubscription records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listUserSubscription(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[UserSubscriptionModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get user_subscription by Id index
   * This function gets data by index.
   */
  async getUserSubscriptionById(
    id: string,
  ): Promise<UserSubscriptionModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_subscription by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserSubscriptionById(
    id: string,
    data: UserSubscriptionModel
  ): Promise<UserSubscriptionModel[]> {
    const index = createIndexId(
      id
    );

    const values = UserSubscriptionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_subscription by Id index
   */
  async deleteUserSubscriptionById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_subscription by UserId index
   * This function gets data by index.
   */
  async getUserSubscriptionByUserId(
    user_id: string,
  ): Promise<UserSubscriptionModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_subscription by UserId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserSubscriptionByUserId(
    user_id: string,
    data: UserSubscriptionModel
  ): Promise<UserSubscriptionModel[]> {
    const index = createIndexUserId(
      user_id
    );

    const values = UserSubscriptionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_subscription by UserId index
   */
  async deleteUserSubscriptionByUserId(
    user_id: string
  ): Promise<void> {
    const index = createIndexUserId(
      user_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_subscription by Tier index
   * This function gets data by index.
   */
  async getUserSubscriptionByTier(
    tier: UserSubscriptionTier,
  ): Promise<UserSubscriptionModel[]> {
    const index = createIndexTier(
      tier
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_subscription by Tier index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserSubscriptionByTier(
    tier: UserSubscriptionTier,
    data: UserSubscriptionModel
  ): Promise<UserSubscriptionModel[]> {
    const index = createIndexTier(
      tier
    );

    const values = UserSubscriptionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_subscription by Tier index
   */
  async deleteUserSubscriptionByTier(
    tier: UserSubscriptionTier
  ): Promise<void> {
    const index = createIndexTier(
      tier
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_subscription by IsActive index
   * This function gets data by index.
   */
  async getUserSubscriptionByIsActive(
    is_active: boolean,
  ): Promise<UserSubscriptionModel[]> {
    const index = createIndexIsActive(
      is_active
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_subscription by IsActive index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserSubscriptionByIsActive(
    is_active: boolean,
    data: UserSubscriptionModel
  ): Promise<UserSubscriptionModel[]> {
    const index = createIndexIsActive(
      is_active
    );

    const values = UserSubscriptionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_subscription by IsActive index
   */
  async deleteUserSubscriptionByIsActive(
    is_active: boolean
  ): Promise<void> {
    const index = createIndexIsActive(
      is_active
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_subscription by DataCreator index
   * This function gets data by index.
   */
  async getUserSubscriptionByDataCreator(
    data_creator: string,
  ): Promise<UserSubscriptionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_subscription by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserSubscriptionByDataCreator(
    data_creator: string,
    data: UserSubscriptionModel
  ): Promise<UserSubscriptionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = UserSubscriptionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_subscription by DataCreator index
   */
  async deleteUserSubscriptionByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get user_subscription by DataUpdater index
   * This function gets data by index.
   */
  async getUserSubscriptionByDataUpdater(
    data_updater: string,
  ): Promise<UserSubscriptionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) user_subscription by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setUserSubscriptionByDataUpdater(
    data_updater: string,
    data: UserSubscriptionModel
  ): Promise<UserSubscriptionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = UserSubscriptionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete user_subscription by DataUpdater index
   */
  async deleteUserSubscriptionByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to UserSubscriptionModel data array
   */
  private resultToData(values: Data[]): UserSubscriptionModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return UserSubscriptionModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as UserSubscriptionModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized UserSubscriptionModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is UserSubscriptionModel => item !== null);
  }
}

/**
 * Convert UserSubscriptionModel data to Value array
 */
function UserSubscriptionModelToValues(data: UserSubscriptionModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'user_id', type: DataType.string, defaultValue: '' },
    { key: 'tier', type: DataType.enumeration, defaultValue: 0 },
    { key: 'started_date', type: DataType.string, defaultValue: '' },
    { key: 'expires_date', type: DataType.string, defaultValue: null },
    { key: 'is_active', type: DataType.boolean, defaultValue: false },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof UserSubscriptionModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to UserSubscriptionModel data
 */
function UserSubscriptionModelFromValues(values: Value[]): UserSubscriptionModel {
  const data: Partial<UserSubscriptionModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'user_id':
        data.user_id = ParseValue(value, DataType.string) as string;
        break;
      case 'tier':
        data.tier = ParseValue(value, DataType.enumeration) as UserSubscriptionTier;
        break;
      case 'started_date':
        data.started_date = ParseValue(value, DataType.string) as string;
        break;
      case 'expires_date':
        data.expires_date = ParseValue(value, DataType.string) as string | null;
        break;
      case 'is_active':
        data.is_active = ParseValue(value, DataType.boolean) as boolean;
        break;
    }
  }
  
  return data as UserSubscriptionModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for UserId fields
 */
function createIndexUserId(
  user_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, user_id, 'user_id'),
  ];

  return {
    fields: ['user_id'],
    values
  };
}
/**
 * Create index for Tier fields
 */
function createIndexTier(
  tier: UserSubscriptionTier
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, tier, 'tier'),
  ];

  return {
    fields: ['tier'],
    values
  };
}
/**
 * Create index for IsActive fields
 */
function createIndexIsActive(
  is_active: boolean
): Index {
  const values: Value[] = [
    CreateValue(DataType.boolean, is_active, 'is_active'),
  ];

  return {
    fields: ['is_active'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default UserSubscriptionORM;