// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: transaction.
// - Entity ID: 102019aed54e5cc7e0a959287341e1fa56d.
// - Entity Version: 102019af1075be77c3886045ea79d1900cd.
// - Task ID: 69337686982efa550d4aac7f.
// - Task Root ID: 69328003c70740a92a92684f.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for TransactionType
 */
export enum TransactionType {
  Unspecified = 0,
  Income = 1,
  Expense = 2,
}



/**
 * Interface for TransactionModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface TransactionModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  amount: number;
  currency: string;
  category: string;
  description?: string | null;
  transaction_date: string;
  type: TransactionType;
  couple_id?: string | null;
}

/**
 * ORM class for Transaction entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class TransactionORM {
  private static instance: TransactionORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019aed54e5cc7e0a959287341e1fa56d';
    this.entityName = 'transaction';
    this.entityVersion = '102019af1075be77c3886045ea79d1900cd';
    this.taskId = '69337686982efa550d4aac7f';
    this.taskRootId = '69328003c70740a92a92684f';
  }

  /**
   * Get singleton instance of TransactionORM
   */
  public static getInstance(): TransactionORM {
    if (!TransactionORM.instance) {
      TransactionORM.instance = new TransactionORM();
    }
    
    return TransactionORM.instance;
  }

  /**
   * Get all Transaction records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllTransaction(): Promise<TransactionModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Transaction record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertTransaction(data: TransactionModel[]): Promise<TransactionModel[]> {
    const structured = data.map((item) => CreateData(TransactionModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Transaction records
   */
  async purgeAllTransaction(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Transaction records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listTransaction(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[TransactionModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get transaction by Id index
   * This function gets data by index.
   */
  async getTransactionById(
    id: string,
  ): Promise<TransactionModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) transaction by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTransactionById(
    id: string,
    data: TransactionModel
  ): Promise<TransactionModel[]> {
    const index = createIndexId(
      id
    );

    const values = TransactionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete transaction by Id index
   */
  async deleteTransactionById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get transaction by CoupleId index
   * This function gets data by index.
   */
  async getTransactionByCoupleId(
    couple_id: string,
  ): Promise<TransactionModel[]> {
    const index = createIndexCoupleId(
      couple_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) transaction by CoupleId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTransactionByCoupleId(
    couple_id: string,
    data: TransactionModel
  ): Promise<TransactionModel[]> {
    const index = createIndexCoupleId(
      couple_id
    );

    const values = TransactionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete transaction by CoupleId index
   */
  async deleteTransactionByCoupleId(
    couple_id: string
  ): Promise<void> {
    const index = createIndexCoupleId(
      couple_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get transaction by TransactionDate index
   * This function gets data by index.
   */
  async getTransactionByTransactionDate(
    transaction_date: string,
  ): Promise<TransactionModel[]> {
    const index = createIndexTransactionDate(
      transaction_date
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) transaction by TransactionDate index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTransactionByTransactionDate(
    transaction_date: string,
    data: TransactionModel
  ): Promise<TransactionModel[]> {
    const index = createIndexTransactionDate(
      transaction_date
    );

    const values = TransactionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete transaction by TransactionDate index
   */
  async deleteTransactionByTransactionDate(
    transaction_date: string
  ): Promise<void> {
    const index = createIndexTransactionDate(
      transaction_date
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get transaction by DataCreator index
   * This function gets data by index.
   */
  async getTransactionByDataCreator(
    data_creator: string,
  ): Promise<TransactionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) transaction by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTransactionByDataCreator(
    data_creator: string,
    data: TransactionModel
  ): Promise<TransactionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = TransactionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete transaction by DataCreator index
   */
  async deleteTransactionByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get transaction by DataUpdater index
   * This function gets data by index.
   */
  async getTransactionByDataUpdater(
    data_updater: string,
  ): Promise<TransactionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) transaction by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setTransactionByDataUpdater(
    data_updater: string,
    data: TransactionModel
  ): Promise<TransactionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = TransactionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete transaction by DataUpdater index
   */
  async deleteTransactionByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to TransactionModel data array
   */
  private resultToData(values: Data[]): TransactionModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return TransactionModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as TransactionModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized TransactionModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is TransactionModel => item !== null);
  }
}

/**
 * Convert TransactionModel data to Value array
 */
function TransactionModelToValues(data: TransactionModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'amount', type: DataType.number, defaultValue: 0 },
    { key: 'currency', type: DataType.string, defaultValue: '' },
    { key: 'category', type: DataType.string, defaultValue: '' },
    { key: 'description', type: DataType.string, defaultValue: null },
    { key: 'transaction_date', type: DataType.string, defaultValue: '' },
    { key: 'type', type: DataType.enumeration, defaultValue: 0 },
    { key: 'couple_id', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof TransactionModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to TransactionModel data
 */
function TransactionModelFromValues(values: Value[]): TransactionModel {
  const data: Partial<TransactionModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'amount':
        data.amount = ParseValue(value, DataType.number) as number;
        break;
      case 'currency':
        data.currency = ParseValue(value, DataType.string) as string;
        break;
      case 'category':
        data.category = ParseValue(value, DataType.string) as string;
        break;
      case 'description':
        data.description = ParseValue(value, DataType.string) as string | null;
        break;
      case 'transaction_date':
        data.transaction_date = ParseValue(value, DataType.string) as string;
        break;
      case 'type':
        data.type = ParseValue(value, DataType.enumeration) as TransactionType;
        break;
      case 'couple_id':
        data.couple_id = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as TransactionModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for CoupleId fields
 */
function createIndexCoupleId(
  couple_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, couple_id, 'couple_id'),
  ];

  return {
    fields: ['couple_id'],
    values
  };
}
/**
 * Create index for TransactionDate fields
 */
function createIndexTransactionDate(
  transaction_date: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, transaction_date, 'transaction_date'),
  ];

  return {
    fields: ['transaction_date'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default TransactionORM;