// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: couple.
// - Entity ID: 102019aed54e5cc7b2b9c61448368f210fc.
// - Entity Version: 102019af1075be77c3886045ea79d1900cd.
// - Task ID: 69337686982efa550d4aac7f.
// - Task Root ID: 69328003c70740a92a92684f.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for CoupleStatus
 */
export enum CoupleStatus {
  Unspecified = 0,
  Pending = 1,
  Active = 2,
  Dissolved = 3,
}



/**
 * Interface for CoupleModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface CoupleModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  partner_one_id: string;
  partner_two_id: string;
  status: CoupleStatus;
}

/**
 * ORM class for Couple entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class CoupleORM {
  private static instance: CoupleORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019aed54e5cc7b2b9c61448368f210fc';
    this.entityName = 'couple';
    this.entityVersion = '102019af1075be77c3886045ea79d1900cd';
    this.taskId = '69337686982efa550d4aac7f';
    this.taskRootId = '69328003c70740a92a92684f';
  }

  /**
   * Get singleton instance of CoupleORM
   */
  public static getInstance(): CoupleORM {
    if (!CoupleORM.instance) {
      CoupleORM.instance = new CoupleORM();
    }
    
    return CoupleORM.instance;
  }

  /**
   * Get all Couple records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllCouple(): Promise<CoupleModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Couple record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertCouple(data: CoupleModel[]): Promise<CoupleModel[]> {
    const structured = data.map((item) => CreateData(CoupleModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Couple records
   */
  async purgeAllCouple(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Couple records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listCouple(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[CoupleModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get couple by Id index
   * This function gets data by index.
   */
  async getCoupleById(
    id: string,
  ): Promise<CoupleModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) couple by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCoupleById(
    id: string,
    data: CoupleModel
  ): Promise<CoupleModel[]> {
    const index = createIndexId(
      id
    );

    const values = CoupleModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete couple by Id index
   */
  async deleteCoupleById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get couple by PartnerOneId index
   * This function gets data by index.
   */
  async getCoupleByPartnerOneId(
    partner_one_id: string,
  ): Promise<CoupleModel[]> {
    const index = createIndexPartnerOneId(
      partner_one_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) couple by PartnerOneId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCoupleByPartnerOneId(
    partner_one_id: string,
    data: CoupleModel
  ): Promise<CoupleModel[]> {
    const index = createIndexPartnerOneId(
      partner_one_id
    );

    const values = CoupleModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete couple by PartnerOneId index
   */
  async deleteCoupleByPartnerOneId(
    partner_one_id: string
  ): Promise<void> {
    const index = createIndexPartnerOneId(
      partner_one_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get couple by PartnerTwoId index
   * This function gets data by index.
   */
  async getCoupleByPartnerTwoId(
    partner_two_id: string,
  ): Promise<CoupleModel[]> {
    const index = createIndexPartnerTwoId(
      partner_two_id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) couple by PartnerTwoId index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCoupleByPartnerTwoId(
    partner_two_id: string,
    data: CoupleModel
  ): Promise<CoupleModel[]> {
    const index = createIndexPartnerTwoId(
      partner_two_id
    );

    const values = CoupleModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete couple by PartnerTwoId index
   */
  async deleteCoupleByPartnerTwoId(
    partner_two_id: string
  ): Promise<void> {
    const index = createIndexPartnerTwoId(
      partner_two_id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get couple by DataCreator index
   * This function gets data by index.
   */
  async getCoupleByDataCreator(
    data_creator: string,
  ): Promise<CoupleModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) couple by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCoupleByDataCreator(
    data_creator: string,
    data: CoupleModel
  ): Promise<CoupleModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = CoupleModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete couple by DataCreator index
   */
  async deleteCoupleByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get couple by DataUpdater index
   * This function gets data by index.
   */
  async getCoupleByDataUpdater(
    data_updater: string,
  ): Promise<CoupleModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) couple by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setCoupleByDataUpdater(
    data_updater: string,
    data: CoupleModel
  ): Promise<CoupleModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = CoupleModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete couple by DataUpdater index
   */
  async deleteCoupleByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to CoupleModel data array
   */
  private resultToData(values: Data[]): CoupleModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return CoupleModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as CoupleModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized CoupleModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is CoupleModel => item !== null);
  }
}

/**
 * Convert CoupleModel data to Value array
 */
function CoupleModelToValues(data: CoupleModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'partner_one_id', type: DataType.string, defaultValue: '' },
    { key: 'partner_two_id', type: DataType.string, defaultValue: '' },
    { key: 'status', type: DataType.enumeration, defaultValue: 0 },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof CoupleModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to CoupleModel data
 */
function CoupleModelFromValues(values: Value[]): CoupleModel {
  const data: Partial<CoupleModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'partner_one_id':
        data.partner_one_id = ParseValue(value, DataType.string) as string;
        break;
      case 'partner_two_id':
        data.partner_two_id = ParseValue(value, DataType.string) as string;
        break;
      case 'status':
        data.status = ParseValue(value, DataType.enumeration) as CoupleStatus;
        break;
    }
  }
  
  return data as CoupleModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for PartnerOneId fields
 */
function createIndexPartnerOneId(
  partner_one_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, partner_one_id, 'partner_one_id'),
  ];

  return {
    fields: ['partner_one_id'],
    values
  };
}
/**
 * Create index for PartnerTwoId fields
 */
function createIndexPartnerTwoId(
  partner_two_id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, partner_two_id, 'partner_two_id'),
  ];

  return {
    fields: ['partner_two_id'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default CoupleORM;